@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

### Creatye user
# @name createUser
POST  {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Júlia Vicentini",
    "email": "xuxu@email.com",
    "passwordHash": "123456"
}

### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "xuxu@email.com",
    "password": "123455"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### Update User
# @name updtaeUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Júlia Atualizada",
    "email": "newxuxu@email.com"
}

### Update User Password
# @name updtaePaasword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPasswordHash": "123455",
    "newPasswordHash": "1234556"
}