@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}
### Auth Login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "userNovo@email.com",
    "password": "123456"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### Creatye user
# @name createUser
POST  {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Júlia Vicentini",
    "email": "xuxu@email.com",
    "passwordHash": "123456"
}

### Update User
# @name updtaeUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{

}